name: Building A Website Using Hugo Server

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read


   
