name: Building A Website Using Hugo Server

on:
  push:
    branches:
      - main
      - dev
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
   
