name: Building A Website Using Hugo Server

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      # Hugo Server SetUp
        - name: Setup Hugo
          uses: peaceiris/actions-hugo@v3
          with:
            hugo-version: '0.145.0'
            extended: true
        - name: Build
          run: hugo --minify

   
