name: Building A Website Using Hugo Server

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
          
      # Hugo Server SetUp
        - name: Setup Hugo
          uses: peaceiris/actions-hugo@v3
          with:
            hugo-version: '0.145.0'
            extended: true
            
        - name: Build
          run: hugo 

        - name: Upload Build Artifact
          uses: actions/upload-artifact@v4
          with:
            name: scalify-tech-blog 
            path: public/**

        - name: Download Build Artifacts
          uses: actions/download-artifact@v4
          with:
            name: scalify-tech-blog 
            
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-region: ${{ secrets.AWS_REGION }}
            role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        - name: Verify AWS Identity
          run : aws sts get-caller-identity
   
